# Generated by Django 5.0.2 on 2024-02-09 10:58

import OrderManagement.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('Merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_date', models.DateField(verbose_name='PO Date')),
                ('po_number', models.CharField(max_length=20, unique=True, verbose_name='PO Number')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total Amount')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Merchant.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='CGST(%)')),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='SGST(%)')),
                ('igst', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='IGST(%)')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Unit Price')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Total Amount')),
                ('hsn_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='HSN Code')),
                ('ean_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='EAN Code')),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='MRP')),
                ('taxable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Taxable Value')),
                ('cgst_value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='CGST Value')),
                ('sgst_value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='SGST Value')),
                ('igst_value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='IGST Value')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.purchaseorder', verbose_name='Purchase Order')),
                ('sku_catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.skucatalogue', verbose_name='SKU Catalogue')),
            ],
            options={
                'verbose_name': 'Purchase Order SKU',
                'verbose_name_plural': 'Purchase Order SKUs',
                'unique_together': {('sku_catalogue', 'purchase_order')},
            },
        ),
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_date', models.DateField(verbose_name='Supply Date')),
                ('status', models.CharField(choices=[('abc', 'abc')], max_length=20, verbose_name='Status')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='Invoice Number')),
                ('courier_partner', models.CharField(choices=[('def', 'def')], max_length=20, verbose_name='Courier Partner')),
                ('courier_poc', models.CharField(max_length=100, verbose_name='Courier POC')),
                ('tracking_id', models.CharField(max_length=50, verbose_name='Tracking ID')),
                ('proof_of_delivery', models.FileField(upload_to=OrderManagement.models.pod_directory_path, verbose_name='Proof Of Delivery')),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.purchaseorder', verbose_name='Purchase Order')),
            ],
            options={
                'verbose_name': 'Supply Order',
                'verbose_name_plural': 'Supply Orders',
            },
        ),
        migrations.CreateModel(
            name='SupplyOrderSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('xyz', 'xyz')], max_length=20, verbose_name='Status')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='CGST(%)')),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='SGST(%)')),
                ('igst', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='IGST(%)')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Unit Price')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Total Amount')),
                ('hsn_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='HSN Code')),
                ('ean_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='EAN Code')),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='MRP')),
                ('taxable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Taxable Value')),
                ('cgst_value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='CGST Value')),
                ('sgst_value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='SGST Value')),
                ('igst_value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='IGST Value')),
                ('purchase_order_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.purchaseordersku', verbose_name='Purchase Order SKU')),
                ('supply_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.supplyorder', verbose_name='Supply Order')),
            ],
            options={
                'verbose_name': 'Supply Order SKU',
                'verbose_name_plural': 'Supply Order SKUs',
                'unique_together': {('supply_order', 'purchase_order_sku')},
            },
        ),
    ]
