# Generated by Django 5.0.2 on 2024-02-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skucatalogue',
            name='ean_code',
            field=models.CharField(max_length=20, verbose_name='EAN Code'),
        ),
        migrations.AlterField(
            model_name='skucatalogue',
            name='hsn_code',
            field=models.CharField(max_length=10, verbose_name='HSN Code'),
        ),
    ]
